### ISSUE TITLE
Build issue - Private Destructor, Puzzle.hpp

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce_2014_cw6#1]
Are the classes Input and Output in puzzle.hpp meant to be public virtual Persistable? Instead of the current implicit private inheritance?

I get the below error without adding public into the lines

In file included from ./user_circuit_sim.hpp:4:
../include/puzzler/puzzles/circuit_sim.hpp:64:9: error: inherited virtual base class 'puzzler::Persistable' has private destructor
  class CircuitSimOutput
        ^
../include/puzzler/core/puzzle.hpp:56:9: note: implicitly declared private here
      : virtual Persistable
        ^~~~~~~~~~~~~~~~~~~

Also amongst the couple of OSX incompatibilities, (clock_gettime being one of them, although we seem to have something they suggest might work but I havnt gone about verifying it myself yet https://gist.github.com/jbenet/1087739

Running the makefile is complaining about the f flag in ar. Why do we need to truncate the names in the archive? Can I safely remove the f flag?

edit: I dont get this error in linux using gcc so I guess clang is being picky?

edit2: Any chance you're free sometime early next week for us to ask you about the codebase? 

edit3:"Note: If you do something complicated in your building of libpuzzler, it should still be possible to build it by going into lib and calling make all." Is this meant to say going into "provider" and calling make all?

**Comment by davidfof13** [comment]
To re-iterate kronocharia's point,

OSX users should change `class Input: virtual Persistable` to `class Input: public virtual Persistable` and also do the same for the Output class. It doesn't change the functionality of the program for me and some compilers such a clang as you pointed think when seeing the former statement that the Class Persistable has a private destructor when it's actually public if you look in `persist.hpp`.

`clock_gettime` doesn't exist in OSX so I created an alias of it. I  added this in  `util.hpp`:

```
// for OSX
// http://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x
#include <sys/time.h>
#define CLOCK_REALTIME 0


#ifdef __MACH__ 
#include <mach/clock.h>
#include <mach/mach.h>

int clock_gettime(int /*clk_id*/, struct timespec * ts){

    clock_serv_t cclock;
    mach_timespec_t mts;
    host_get_clock_service(mach_host_self(), CALENDAR_CLOCK, &cclock);
    clock_get_time(cclock, &mts);
    mach_port_deallocate(mach_task_self(), cclock);
    ts->tv_sec = mts.tv_sec;
    ts->tv_nsec = mts.tv_nsec;

    return 0;
}

#endif
```

and it works well
