### ISSUE TITLE
matrix multiplication typo?

### ISSUE THREAD

**Issue by reginalio** [HPCE/hpce_2014_cw6#4]
In the MatrixMul function in **include/puzzler/puzzles/matrix_exponent.hpp**

```
static std::vector<uint32_t> MatrixMul(unsigned n, std::vector<uint32_t> a, std::vector<uint32_t> b)
{
      std::vector<uint32_t> res(n*n, 0);

      for(unsigned r=0; r<n; r++){
        for(unsigned c=0; c<n; c++){
          for(unsigned i=0; i<n; i++){
            res[r*n+c] = Add(res[r*n+c], Mul(a[r*n+i], b[i*n+r]));
          }
        }
      }
      return res;
}
```

Should the `b[i*n+r]` be `b[i*n+c]` instead?

**Comment by m8pple** [comment]
Sorry it's taken so long to get back to you on this. It was originally part of
a "side quest", but I forgot to take it out when I simplified the coursework.
So yes, it is a bug. However, at this point probably too many people have designed
solutions around it, so I don't really want to change the spec.

So while you're correct, and thank-you for the bug report, I'm going to leave
it as a WillNotFix.

(An interesting question is whether it exposes optimisation opportunities).
