### ISSUE TITLE
Generating large reference outputs using create and execute_puzzle

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce_2014_cw6#7]
I tried running this
`./bin/create_puzzle_input life 1000 2 | ./bin/execute_puzzle 1 2 > life1000ref.out`
but I end up with the error :
Caught exception : StdoutStream::Recv - Not all data was received.

The max I can seem to do is around 720 ish
However size 1000 with run_puzzle seems to be fine. Has anyone encountered this?

This doesnt seem to be a problem with the other puzzle types that I can tell

**Comment by davidfof13** [comment]
I also encountered this problem. I think it's a mac issue. I'm running all my tests on DoC machines now. I have no problems there

**Comment by kronocharia** [comment]
It doesn't work in cygwin too, or so I'm told

**Comment by davidfof13** [comment]
Try ssh'ing to a graphics machine. I just ran your command there and it's working. Just a note, not all of them have OpenCL working but graphic07 seems to  be fine

**Comment by m8pple** [comment]
Confirmed under cygwin64 (did my original testing under linux).

A fix is to generate to a file then read it back out:

```
./bin/create_puzzle_input life 1000 2 > life1000.in; < life1000.in ./bin/execute_puzzle 1 2 life1000ref.out
```

I suspect I've done something wrong on the pipe read, and not dealt with situations where it partially
reads the block of data. IIRC linux will block in that scenario.

**Comment by kronocharia** [comment]
Is the code change meant to replace the need to read in and back out? As its still throwing exceptions after pulling new code

Im doing this in one of my test scripts, and its giving me the same error still, however on even smaller sizes too. Theyre affect life and matrix, which we've accelerated with opencl, is it possible its being caused on our end too? They work fine with run_puzzle though

`cat $FNAME_IN | ./$EXECPATH/execute_puzzle 0 1 > tmp.out`
`./$EXECPATH/compare_puzzle_output "$FNAME" tmp.out 2`

**Comment by m8pple** [comment]
It fixes the streaming, or at least it does for me on cygwin64 (and still works on linux).

This is still on a mac presumably?

The only thing I can conceive of is that read(.) is returning zero to indicate that the data
is not ready yet. That _seems_ to be breaking the spec of read, as zero indicates end of
file, or that it is in non-blocking mode (which I assume stdin is not).

The latest commit puts in two error messages (one for zero, one for fail), which might
tell you which path is failing.

**Comment by kronocharia** [comment]
The errors now in Caught exception : FileInStream::Recv - Not all data was recieved. Perhaps the change also needs to be applied there?

edit: I tried adding the change to there too, and we're back to stdoutstream for matrix, life 100seems fine now though, working on making new 1000 size inputs

edit2: Life 1000 works fine now, the issue with matrix is probably on our end

**Comment by m8pple** [comment]
Ah, was this using process substitution? I didn't change FileInStream. If you apply the changes in
StdinStream to FileInStream the error should go away.

**Comment by kronocharia** [comment]
It wasn't substitution? Just catting in the generated input files?

**Comment by m8pple** [comment]
Ok, sounds like this can be closed. Not sure what the ultimate problem was.
